name: Test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

env:
  SKIP_INTEGRATION_TESTS: 'true'

jobs:

  spm_macos:
    name: SPM, macOS ${{ matrix.macOS }}, Xcode ${{ matrix.xcode }}
    runs-on: namespace-profile-macos-m4-6cpu-14ram
    strategy:
      matrix:
        include:
          - macOS: '15'
            xcode: '16.4'
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
    steps:
      - name: Checkout repository
        uses: namespacelabs/nscloud-checkout-action@v8
      - name: Use Xcode ${{ matrix.xcode }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Cache Swift PM dependencies
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: |
            swiftpm
            xcode
      - name: Run tests
        run: make spm_test
