name: Test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

env:
  SKIP_INTEGRATION_TESTS: 'true'

jobs:

  spm_macos:
    name: SPM, macOS ${{ matrix.macOS }}, Xcode ${{ matrix.xcode }}
    runs-on: namespace-profile-mac-cache
    strategy:
      matrix:
        include:
          - macOS: '15'
            xcode: '16.4'
    steps:
      - name: Checkout repository
        uses: namespacelabs/nscloud-checkout-action@v8
      - name: Setup Xcode & Swift cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: |
            xcode
            swift
            ruby
      - name: Select Xcode 16.4
        run: |
          if [ -d "/Applications/Xcode_16.4.app" ]; then
            sudo xcode-select -s /Applications/Xcode_16.4.app
          fi
      - name: Run tests
        run: make spm_test
